#!/usr/bin/env python

'''convenience script to start **specscan** locally (keep this out of the MANIFEST)'''

import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), 'lib')))
import dtxrd.start_specscan as script
script.main()
