.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 Stanislav Stoupin <sstoupin@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH THROUGHPUT 1 "February 13, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
throughput \- calculate throughput of a multicrystal configuration 
(dynamical theory of x-ray diffraction for perfect crystals)
.SH SYNOPSIS
.B throughput
.RI [ options ] \ "parameters" \ "input_file" 
.\".br
.\".B bar
.\".RI [ options ] "files" ...
.\"
.SH DESCRIPTION
A program to calculate throughput of a multicrystal configuration given by input_file 
using dynamical theory of x-ray diffraction for perfect crystals
.br
For a brief summary of options and parameters run "throughput -h".
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.\" \fBpython-dtxrd-1.0\fP is a program that...
.SH PARAMETERS
"parameters" = "func dpsi Ec dEx ne"
.TP
.B func 
angular divergence distribution function for incoming x-rays:
.br 
func=g - Gaussian
.br
func=l - Lorentzian
.TP
.B dpsi
angular divergence in units of [urad] 
.br
rms for Gaussian distribution
.br
fwhm for Lorentzian distribution
.br
.TP
.B Ec
central energy for energy distribution in units of [keV] 
(corrected automatically depending on the choice of source 
and presence of crystals in backscattering configuration 
in the input file)
.TP
.B dEx 
energy half-range in units of [meV]
.TP
.B ne
number of steps in the energy grid to perform the calculation (max 1000)
.SH OPTIONS
.TP
.B \-v, \-\-version
show version of program.
.TP
.B \-h, \-\-help
show summary of options.
.TP
.B \-o F, \-\-output=F 
write results to file F (default to stdout)
.TP
.B \-w D, \-\-write=D 
write data to file D (default - no action)
.TP
.B \-p, \-\-pi
pi polarization for incident wave (default - s polarization)
.TP
.B \-a NTH, \-\-angular_scan=NTH
perform crystal rotation (angular scan) with NTH points
.TP
.B \-s SRC, \-\-source=SRC
type of energy distribution for the source:
.br
SRC=0 - flat distribution (default) 
.br
SRC=1 - Cu K-alpha source 
.br
SRC=9 - energy distribution from file source_e.dat 
.\".TP
.SH SEE ALSO
.BR dtxrd (1),
.BR rcpeak (1).
.TP
.SH AUTHOR
Stanislav Stoupin <sstoupin@gmail.com>
