.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 Stanislav Stoupin <sstoupin@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DTXRD 1 "February 13, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dtxrd \- x-ray diffraction calculator (dynamical theory of x-ray
diffraction for perfect crystals)
.SH SYNOPSIS
.B dtxrd
.RI [ options ] \ "parameters" 
.br
example: Si 1 1 1 0 0 300 1 e 8
.\".br
.\".B bar
.\".RI [ options ] "files" ...
.\"
.SH DESCRIPTION
A program to calculate parameters of a single Bragg reflection for a 
monochromatic incident wave using dynamical theory of x-ray diffraction
for perfect crystals
.br
For a brief summary run "dtxrd -h".
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.\" \fBpython-dtxrd-1.0\fP is a program that...
.SH PARAMETERS
"parameters" = "crystal h k l eta phi T d flag theta(or Ex)"
.TP
.B crystal
crystal type: C (diamond), Si (silicon), Ge (germanium) or Al2O3 (sapphire)
.TP
.B h k l
Miller indicies of a chosen Bragg reflection
.TP
.B eta
asymmetry angle 
.TP
.B phi
asimuthal angle of incidence
.TP
.B T
crystal temperature [K]
.TP 
.B d
crystal thickness [mm]
.TP
.B flag
flag=a - perform calculation at a given glancing angle of incidence 
.B theta
.br
flag=e - perform calculation at a given photon energy 
.B Ex
.\"
.SH OPTIONS
.TP
.B \-v, \-\-version
show version of program.
.TP
.B \-h, \-\-help
show summary of options.
.TP
.B \-o F, \-\-output=F 
write results to file F (default to stdout)
.TP
.B \-w D, \-\-write=D 
write data to file D (default - no action)
.TP
.B \-p, \-\-pi
pi polarization for incident wave (default - s polarization)
.TP
.B \-c, \-\-conv
convolve data with a virtual instrumental resolution function having FWHM of
1/10 of the Darwin width and report the resulting FWHM of the reflectivity
curve
.\".TP
.SH SEE ALSO
.BR throughput (1),
.BR rcpeak (1).
.TP
.SH AUTHOR
Stanislav Stoupin <sstoupin@gmail.com>
